from typing import Protocol

from integration_api.models.responses import AvailablePort


class ESwitchAdapter(Protocol):
    def is_ready(self) -> bool: ...
    def create_vswitch(self, vswitch_id: int) -> None: ...
    def delete_vswitch(self, vswitch_id: int) -> None: ...
    def list_available_ports(self) -> list[AvailablePort]: ...
    def attach_port(self, vswitch_id: int, port_id: int) -> None: ...
    def detach_port(self, vswitch_id: int, port_id: int) -> None: ...
